spring.application.name=cocomall-search
server.port=8080

spring.thymeleaf.cache=false

spring.redis.port=6379
spring.session.store-type=redis

management.endpoints.web.exposure.include=*
feign.sentinel.enabled=true


spring.redis.host=redis.cocomall
spring.cloud.sentinel.transport.dashboard=sentinel-service.cocomall:8333
spring.cloud.nacos.discovery.server-addr=nacos-service.cocomall:8848
spring.zipkin.base-url=http://zipkin-service.cocomall:9411/

#服务追踪
#关闭服务发现
spring.zipkin.discovery-client-enabled=false
spring.zipkin.sender.type=web
#配置采样器
spring.sleuth.sampler.probability=1