spring.cache.type=redis

spring.cache.redis.time-to-live=3600000
#如果指定了前缀就用我们指定的前缀，如果没有就默认使用缓存的名字作为前缀
#spring.cache.redis.key-prefix=CACHE_
spring.cache.redis.use-key-prefix=true
#是否缓存空值，防止缓存穿透
spring.cache.redis.cache-null-values=true

spring.session.store-type=redis

cocomall.thread.core-size=20
cocomall.thread.max-size=200
cocomall.thread.keep-alive-time=10

management.endpoints.web.exposure.include=*

feign.sentinel.enabled=true


spring.redis.host=redis.cocomall
spring.cloud.sentinel.transport.dashboard=sentinel-service.cocomall:8333
spring.cloud.nacos.discovery.server-addr=nacos-service.cocomall:8848
spring.zipkin.base-url=http://zipkin-service.cocomall:9411/

#服务追踪
#关闭服务发现
spring.zipkin.discovery-client-enabled=false
spring.zipkin.sender.type=web
#配置采样器
spring.sleuth.sampler.probability=1