spring:
  cloud:
    alicloud:
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        template-id: 908e94ccf08b4476ba6c876d13f084ad
        appcode: c4c82c1a95774b15a63b022d0984aae8

server:
  port: 8080